name: Update Report
on:
  push:
    branches:
      - master
jobs:
  updateContent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Update Report
        run: |
          git log --format='%aN <%aE>%n%cN <%cE>' | sort -u > Report
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: update Report
          title: Update Report
          body: Content Updated
          branch: main
